### ISSUE TITLE
Ability to set max results and offset for predefined rest queries

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/fts#11]
Typical usage: implement /recent query that returns 10 last orders / payments / etc
We want to set limit on server as business requirement

---
Original issue: https://youtrack.haulmont.com/issue/PL-9483

**Comment by jreznot** [comment]
Issue moved to [cuba-platform/cuba #844](https://github.com/cuba-platform/cuba/issues/844) via [**ZenHub**](https://www.zenhub.com/)
