### ISSUE TITLE
Provide an easy way to specify custom analyzer for FTS IndexWriter

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/fts#12]
Now there is a static method LuceneWriter.createWriter that creates an IndexWriter with EntityAttributeAnalyzer. There may be cases when we want another analyzer (to split text into tokens with some other rules). The current analyzer doesn't allow to have tokens with dots, for example "A.14.45" won't be searched. The Lucene StandardAnalyzer allows this search.

---
Original issue: https://youtrack.haulmont.com/issue/PL-9636

**Comment by gorbunkov** [comment]
Implemented during FTS refactoring. The `com.haulmont.fts.core.sys.IndexWriterProviderBean#createAnalyzer` method can be overriden
