### ISSUE TITLE
Add PUT mapping for REST API v2 invokeServiceMethod

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/fts#21]
Although we can't control what service call does, it is worth keeping correct HTTP contract for the call - during migrating to CUBA's REST API from a different API, for instance.

---
Original issue: https://youtrack.haulmont.com/issue/PL-10588

**Comment by jreznot** [comment]
Issue moved to [cuba-platform/cuba #842](https://github.com/cuba-platform/cuba/issues/842) via [**ZenHub**](https://www.zenhub.com/)
