### ISSUE TITLE
Optimize FTS search performance

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/fts#26]
FtsServiceBean.makeSearchResult uses the DataManager for reloading each entity of the Lucene search result. This is done to check security constraints. A new query in a new transaction is executed for each entity. We can execute query not for the single, but for the batch of entities.

---
Original issue: https://youtrack.haulmont.com/issue/PL-10748

**Comment by andreysubbotin** [comment]
- FTS Search shows results grouped by entity metaclass 
- FTS Search screen uses page buttons in the bottom of the screen like a Google. This buttons are used for navigation between pages of the results. Next page button clear previous results and show new page. Next page button is disabled on the last search page.
- `More` button is removed from each group of the result. You can see new results using "Next" page button.
- System stored last searched Lucene document. Document is used for open next page from the index

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[0628ff1b](https://git.haulmont.com/platform/fts/commit/0628ff1b56c04d3e385cf3647332ffcf001ef551) in **release_6_10** - Optimize FTS search performance #26

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[6491d74e](https://git.haulmont.com/platform/fts/commit/6491d74e254f4a3369f863a5b257ef08db1e49b4) in **master** - Optimize FTS search performance #26

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[d600d48d](https://git.haulmont.com/platform/fts/commit/d600d48d7983e24e78a5cdf048b4d2f74a449784) in **master** - Optimize FTS search performance #26

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[d412c7e7](https://git.haulmont.com/platform/fts/commit/d412c7e720fbf43b2d7df87feaf1391cf5b3f808) in **master** - Optimize FTS search performance #26

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[e0282d09](https://git.haulmont.com/platform/fts/commit/e0282d0916bb63f18544fa774da3cc402d64ebc7) in **master** - Optimize FTS search performance #26

Run test configuration

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[cfed370a](https://git.haulmont.com/platform/fts/commit/cfed370a80cab514f9479cec9a3b24068fec20a6) in **release_6_10** - Optimize FTS search performance #26

Run test configuration
