### ISSUE TITLE
Instances of different entities with the same IDs are not found

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/fts#33]
### Environment

- Platform version: 6.9.4 

### Description of the bug or enhancement

- Minimal reproducible example
1) create three IntId/IntIdentity entities (For Long*Id and StringId - absolutely the same)
2) create standard screens for it 
3) enable FTS in the project
4) Create several instances of the entities. Save *the same values* in some fields of this entities
5) Reindex all
All the entities are saved to queue
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/dc0f79da-5667-4599-abf0-cf76e3e59cd3)

6) Proces queue
7) FTS search *by the value*

- Actual behavior
Entities with the same IDs are exluded from search results
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/a9c36c2d-36d3-4b3c-9585-12dda66d2d95)

**Comment by andreysubbotin** [comment]
Fixed in cuba-platform/fts#47
