### ISSUE TITLE
FTS add-on localization doesn't work

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/fts#35]
#### Environment

- Platform version: 6.9.5

#### Description of the bug or enhancement
1. Create a new project
2. Add the `fts` component
3. Add a new language (Spanish, for example) to the project
4. Add the component localization, as it is described in the `translations` addon
5. Run the app, reindex some entities
6. Try to find something

**A.R.** Notifications and captions are not localized
**Workaround:** add the path to the localisation: `com.haulmont.fts.web` to the `cuba.mainMessagePack` property in the `web-app.properties` file.

Relates to https://github.com/cuba-platform/translations/issues/40

**Comment by haulmont-git** [comment]
Git changesets by `artamonov`: 

[1f7462b2](https://git.haulmont.com/platform/fts/commit/1f7462b2be5b50076a57dd717c607a1d3aac5cd7) in **master** - FTS add-on localization doesn't work #35

**Comment by haulmont-git** [comment]
Git changesets by `artamonov`: 

[a61afbcc](https://git.haulmont.com/platform/fts/commit/a61afbccd6b987f5c020c88f21016389a637217b) in **release_6_10** - FTS add-on localization doesn't work #35
