### ISSUE TITLE
NoSuchMethodException: org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTPictureBaseImpl.<init> for entity with office attachment

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/fts#36]
https://www.cuba-platform.com/discuss/t/error-in-logging-from-full-text-search-after-platform-update-to-6-9-5/6428

### Environment

- Platform version: 6.9.0
### Description of the bug or enhancement
Error is reproduced for entity with DOCX attachment
Attachment: 
[blog post.docx](https://github.com/cuba-platform/fts/files/2400804/blog.post.docx)

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[a3439926](https://git.haulmont.com/platform/fts/commit/a3439926badef5395128c11c34484ae12ee9dde1) in **release_6_10** - NoSuchMethodException: org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTPictureBaseImpl.<init> for entity with office attachment#36

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[3a7bbac2](https://git.haulmont.com/platform/fts/commit/3a7bbac2c40bcc638d6cf0b47d3d85f9fbfcb6f7) in **master** - NoSuchMethodException: org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTPictureBaseImpl.<init> for entity with office attachment#36
