### ISSUE TITLE
Fts search window doesn't show last empty page

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/fts#37]
### Environment

- Platform version: 6.10

### Description of the bug or enhancement
AR: When user click Next page and page is empty, system shows empty page. 
ER: System must show notification "Nothing to found" and haven't to show empty page

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[cd7b9011](https://git.haulmont.com/platform/fts/commit/cd7b9011507f7256b8dc4539052fa0c611c73a5d) in **release_6_10** - Fts search window doesn't show last empty page #37

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[f42b8f07](https://git.haulmont.com/platform/fts/commit/f42b8f073ca9e78aa0d63578489a7898e88a65e5) in **master** - Fts search window doesn't show last empty page #37
