### ISSUE TITLE
Search window doesn't show results for file

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/fts#40]
### Environment

- Platform version: 6.10.0
### Description of the bug or enhancement
- Minimal reproducible example
  - Create model: entity with reference to FileDescriptor
  - Start application. Create entity with file.
  - Index entity
  - Find entity in the search window by file content
- Expected behavior
Entity should be found
- Actual behavior
Entity isn't found

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[7f1d2423](https://git.haulmont.com/platform/fts/commit/7f1d2423b41fb68ef6b0f00e71ff57fd189e4600) in **release_6_10** - Search window doesn't show results for file #40

**Comment by andreysubbotin** [comment]
> ### Environment
> * Platform version: 6.10.0
> 
> ### Description of the bug or enhancement
> * Minimal reproducible example
>   
>   * Create model: entity with reference to FileDescriptor
>   * Start application. Create entity with file.
>   * Index entity
>   * Find entity in the search window by file content
> * Expected behavior
>   Entity should be found
> * Actual behavior
>   Entity isn't found

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[661f863a](https://git.haulmont.com/platform/fts/commit/661f863a39905118d56e5d78b8366b84897a4564) in **master** - Search window doesn't show results for file #40

**Comment by myatlevEvg** [comment]
Please check this issue on 7.0 platform after closing this [YouTrack](https://youtrack.cuba-platform.com/issue/STUDIO-4837#u=1538640107370) issue
