### ISSUE TITLE
FtsManager.reindexNextBatch() doesn't put records to the FTS queue

### ISSUE THREAD

**Issue by gorbunkov** [cuba-platform/fts#45]
Forum topic: https://www.cuba-platform.com/discuss/t/fts-reindexnextbatch-doesnt-seem-to-be-working/7131

**Comment by haulmont-git** [comment]
Git changesets by `gorbunkov`: 

[c04048b7](https://git.haulmont.com/platform/fts/commit/c04048b78cd60e623a81cacc2451b9dddfb9f88e) in **release_6_10** - FtsManager.reindexNextBatch() doesn't put records to the FTS queue #45

**Comment by haulmont-git** [comment]
Git changesets by `gorbunkov`: 

[235ae1c5](https://git.haulmont.com/platform/fts/commit/235ae1c59ca85fa452cd5c925e108bc02e520d0f) in **master** - FtsManager.reindexNextBatch() doesn't put records to the FTS queue #45
