### ISSUE TITLE
Expose LRUQueryCache statistics to JMX

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/fts#48]
### Description of the bug or enhancement
Lucene has global cache LRUQueryCache stored in org.apache.lucene.search.IndexSearcher#DEFAULT_QUERY_CACHE field.

From LRUQueryCache javadocs:
> This cache exposes some global statistics (hit count, miss count, number of cache entries, total number of DocIdSets that have ever been cached, number of evicted entries).

I think this can be useful for monitoring, if we expose it through jmx attributes.

**Comment by andreysubbotin** [comment]
Git changes: https://git.haulmont.com/platform/fts/commit/0bf481cb91da0e3cd3ed40eccae0a990e1183d47

**Comment by andreysubbotin** [comment]
@alexbudarov, We can move to 6.8 if needed
