### ISSUE TITLE
Update Spring version to 5.1

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/fts#51]
### Description of the bug or enhancement
Remove xsi:schemaLocation from spring.xml

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[ba64b944](https://git.haulmont.com/platform/fts/commit/ba64b944e3c3dcfadf1824b608e7947b97ab55a8) in **master** - Update Spring version to 5.1 #51

Remove xsi:schemaLocation from spring.xml
