### ISSUE TITLE
Show Lucene index format version in jmx

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/fts#52]
### Environment
- Platform version: 6.8 - 6.10

### Description of the bug or enhancement
Let's imagine I'm upgrading my system from CUBA 6.8 to 6.10.
I see that there is a Lucene version increase, so I probably need to upgrade my indices.

But how do I determine if the index has been already upgraded or not? For example if I check actions of other employees who performed the update of the system.
Given the fact that Lucene 7.2.1 works without errors with indices created by 6.6.0. Is the upgrade necessary after all, was the format changed or not?

So it would be nice to see in JMX "latest index version" and "version of indices on disk".

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[f7924842](https://git.haulmont.com/platform/fts/commit/f7924842bd7940919c068fe6947e46c756984c48) in **master** - Show Lucene index format version in jmx #52

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[5d2ef88a](https://git.haulmont.com/platform/fts/commit/5d2ef88a6409f08476fb1b3dc534e40a36a7ef3c) in **release_6_10** - Show Lucene index format version in jmx #52

**Comment by andreysubbotin** [comment]
`FtsManagerMbean.getIndexFormatVersion` returns current index format version 
`FtsManagerMbean.getLatestIndexFormatVersion` returns last index format version supported by lucene
