### ISSUE TITLE
Fts cannot find roles after reindexing

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/fts#59]
### Environment
- Platform version: 7.2
- Client type: Web

### Description of the bug or enhancement
- Minimal reproducible example
1. Create demo project with 7.2 version
2. Follow the tutorial about how to configure FTS ([documentation](https://doc.cuba-platform.com/fts-7.0/qs_project_setup.html))
3. Try to search "adm"
- Expected behavior
FTS will find:
UserRole - Administration
User - admin
- Actual behavior
Only User - admin

In 7.1 it works as expected. After migration project to 7.2, reindexing and processing queue it starts work wrong.

**Comment by gorbunkov** [comment]
Caused by https://issues.apache.org/jira/browse/LUCENE-8498
