### ISSUE TITLE
FTS for browser screens loads immediately hit infos and tooltip description for all searched entities

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/fts#60]
### Environment

- Platform version: 7.0

### Description of the bug or enhancement
   - FTS for browser screens loads immediately hit infos and tooltip description for all searched entities
   - It consumes a lot of memory
   - Try to load tooltip information lazy, when you clicked on an entity in a browser screen.
   - Thesis dependent changes: https://git.haulmont.com/thesis/app/blob/master/modules/web/src/com/haulmont/thesis/web/gui/components/filter/LazyHitInfoMap.java
- Minimal reproducible example
  - Entity model: an entity with attachments
  - Create instances of the entity with attachments. Attachment files must be large.
  - Try to find by FTS condition in the entity browser. 
  - Check a memory consumption by heap dump.

**Comment by gorbunkov** [comment]
For QA: tooltips are generated for displayed entities only. Check that if there are a lot of indexed entities (thousands) that meet full-text- search criteria, no out-of-memory errors appear.

**Comment by gorbunkov** [comment]
Breaking change - for old projects, users will have to set the `cuba.gui.genericFilterFtsTableTooltipsEnabled` property manually if they need tooltips.
