### ISSUE TITLE
Display FTS tooltips in DataGrid component

### ISSUE THREAD

**Issue by gorbunkov** [cuba-platform/fts#65]
When a full-text search is done using the generic filter component a tooltip with hit information is added to each line of the Table component. 
The same should happen for the DataGrid as well.

**Comment by gorbunkov** [comment]
Commit in CUBA: https://github.com/cuba-platform/cuba/commit/c560ac3f18f9b4e1cdbec44efa53df050ca07aa4

**Comment by natfirst** [comment]
Tooltip displays with tags
![image](https://user-images.githubusercontent.com/17950251/68772771-d12a3080-0643-11ea-9f02-0fb60bcf61cb.png)
