### ISSUE TITLE
Slow fts tooltips initialization in case of many table cells

### ISSUE THREAD

**Issue by Ilya-c** [cuba-platform/fts#73]
### Environment

- Platform version: 7.2.1

### Description of the bug or enhancement

1. Enable tooltips in tables with fts filters cuba.gui.genericFilterFtsTableTooltipsEnabled=true
2. Find some entities using fts search

- Expected behavior: generate only single HitInfo for the each table row
- Actual behavior: HitInfo's are generated for each cell of the table row

**Comment by gorbunkov** [comment]
Fixed in cuba-platform/cuba#2776
