### ISSUE TITLE
Could not find com.haulmont.gradle:cuba-plugin:7.3-SNAPSHOT

### ISSUE THREAD

**Issue by ETHwsch** [cuba-platform/fts#75]
If I try to load the project with the latest version of CUBA and I am getting the error message:
Could not find com.haulmont.gradle:cuba-plugin:7.3-SNAPSHOT

See here the CUBA version I am using:
![image](https://user-images.githubusercontent.com/12100648/84594080-10c23080-ae50-11ea-894e-cb46700845ec.png)

**Comment by knstvk** [comment]
Make sure you are using the correct repository: https://repo.cuba-platform.com/content/groups/work, see [docs](https://doc.cuba-platform.com/manual-7.2/access_to_repo.html).
If it still doesn't work, create a topic at https://www.cuba-platform.com/discuss/c/support
