### ISSUE TITLE
Changes are not registered in the Entity log

### ISSUE THREAD

**Issue by skatova** [cuba-platform/fts#82]
### Environment

- Platform version: 7.2.10
- Forum issue: https://www.cuba-platform.com/discuss/t/entity-log-with-fts-problem/14327

### Description of the bug or enhancement

- Minimal reproducible example
1. Run attached project
2. Сonfigure **Entity log** for entity **Place**
3. Сreate an entry (or modify an existing) for entity **Place**
4. Open **Entity log**
- Expected behavior
The change registered in the Entity log
- Actual behavior
The change did not register in the Entity log

If remove an entry for entity **Place** from the **fts.xml** file, restart the project and create a new entry for entity **Place** the change in the **Entity log** will be registered.

Attached project: [hfc.zip](https://github.com/cuba-platform/fts/files/5696649/hfc.zip)

**Comment by andreysubbotin** [comment]
Changes 7.3: https://github.com/cuba-platform/cuba/commit/668aa6766f3ea30d464f5d6dc9b71effaf68e2b0
Changes 7.2: https://github.com/cuba-platform/cuba/commit/5ae6e20686c330c24a418a0170eba72fc2fa9707
