### ISSUE TITLE
ReindexNextBatch method works incorrectly with searchableIf script

### ISSUE THREAD

**Issue by Ilya-c** [cuba-platform/fts#84]
### Environment

- Platform version: 7.2.10

### Description of the bug or enhancement

- For example we have 5600 entities to reindex  
- In the first iteration we trying to enqueue 5000 entities according to the propert fts.reindexBatchSize
- If we have <searchableIf> script and script conditions for some of the entities aren't satisfied next batch (next 600 entities) won't be processed because of incorrect "if" in the FtsManager#reindexNextBatch method:
```
if (ids.size() < ftsConfig.getReindexBatchSize()) {
    reindexEntitiesQueue.remove();
    ftsSender.emptyFakeQueue(metaClass.getName());
}
```
Here ids contains only ids of the entities with satisfied "searchableIf" script. Here we should compare count of the objects, returned by the ```collector.loadResults()``` method as it was in previous version (checked in version 5.9).

**Comment by Gavrilov-Ivan** [comment]
https://upsource.haulmont.com/platform-fts-git/review/FTS-CR-11
